"""Export a project's data + insights + logo/QR/background images from a running
local backend into frontend/src/archive/archive-data.ts and archive-assets.ts, for
the offline single-file archive build (npm run build:archive).

Usage: python scripts/export-archive-data.py [backend_base_url] [project_id]
Defaults to the local dev backend on port 8091, project 5.
"""
import base64
import json
import sys
import urllib.request
from pathlib import Path

BASE = sys.argv[1] if len(sys.argv) > 1 else 'http://127.0.0.1:8091/api'
PROJECT_ID = sys.argv[2] if len(sys.argv) > 2 else '5'
PROJECT_BASE = f'{BASE}/projects/{PROJECT_ID}'

DATA_TYPES = ['bht', 'sales', 'ad_spend', 'creatives', 'ecom', 'perception', 'digital', 'media_details', 'neuro', 'wordstat']

FRONTEND_DIR = Path(__file__).resolve().parent.parent
ARCHIVE_DIR = FRONTEND_DIR / 'src' / 'archive'
PUBLIC_DIR = FRONTEND_DIR / 'public'

ARCHIVE_DIR.mkdir(parents=True, exist_ok=True)


def fetch_json(url: str):
    with urllib.request.urlopen(url) as resp:
        return json.loads(resp.read())


def main():
    out = {'project': None, 'availableTypes': [], 'data': {}, 'insights': None}

    proj = fetch_json(PROJECT_BASE)
    out['project'] = {'id': proj['id'], 'name': proj['name']}

    snaps = fetch_json(f'{PROJECT_BASE}/snapshots')
    out['availableTypes'] = sorted(set(s['data_type'] for s in snaps if s['data_type'] != 'insights'))

    for data_type in DATA_TYPES:
        try:
            out['data'][data_type] = fetch_json(f'{PROJECT_BASE}/data/{data_type}')
        except Exception as e:
            print(f'  skip {data_type}: {e}')

    out['insights'] = fetch_json(f'{PROJECT_BASE}/insights')

    data_ts = ARCHIVE_DIR / 'archive-data.ts'
    data_ts.write_text(
        '/* eslint-disable */\n'
        '// Auto-generated by scripts/export-archive-data.py. Do not edit by hand.\n'
        'export const ARCHIVE_DATA: any = ' + json.dumps(out, ensure_ascii=False) + ';\n',
        encoding='utf-8',
    )
    print(f'Wrote {data_ts} ({data_ts.stat().st_size} bytes)')
    print('  availableTypes:', out['availableTypes'])
    print('  insights keys:', [k for k in out['insights'].keys() if k not in ('available', 'generatedAt')])

    assets = {}
    for key, (fname, mime) in {
        'sidebarBg': ('sidebar-bg.png', 'image/png'),
        'logo': ('horizons-pulse-logo.png', 'image/png'),
        'qr': ('share-qr.jpg', 'image/jpeg'),
    }.items():
        raw = (PUBLIC_DIR / fname).read_bytes()
        assets[key] = f'data:{mime};base64,{base64.b64encode(raw).decode("ascii")}'

    assets_ts = ARCHIVE_DIR / 'archive-assets.ts'
    assets_ts.write_text(
        '/* eslint-disable */\n'
        '// Auto-generated by scripts/export-archive-data.py. Base64-embedded images for the offline archive build.\n'
        'export const ARCHIVE_ASSETS: { sidebarBg: string; logo: string; qr: string } = '
        + json.dumps(assets) + ';\n',
        encoding='utf-8',
    )
    print(f'Wrote {assets_ts} ({assets_ts.stat().st_size} bytes)')


if __name__ == '__main__':
    main()
